"""initial schema: facilities, users, patients, visits, risk_flags, reviews, refresh_tokens, audit_log

Revision ID: 91595bfd8f8a
Revises: 
Create Date: 2026-08-18 22:52:05.487196

"""
from alembic import op
import sqlalchemy as sa
from app.db.uuid_types import GUID


# revision identifiers, used by Alembic.
revision = '91595bfd8f8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facilities_name', 'facilities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('facility_id', GUID(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_facility_id', 'users', ['facility_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('user_id', GUID(length=16), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('worker_id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=False),
    sa.Column('edd', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patients_created_at', 'patients', ['created_at'], unique=False)
    op.create_index('ix_patients_worker_id', 'patients', ['worker_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('user_id', GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('patient_id', GUID(length=16), nullable=False),
    sa.Column('doctor_id', GUID(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1500), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_doctor_id', 'reviews', ['doctor_id'], unique=False)
    op.create_index('ix_reviews_patient_id', 'reviews', ['patient_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.create_table('visits',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('patient_id', GUID(length=16), nullable=False),
    sa.Column('worker_id', GUID(length=16), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('blood_sugar', sa.Integer(), nullable=True),
    sa.Column('body_temp_c', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('created_locally_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visits_created_locally_at', 'visits', ['created_locally_at'], unique=False)
    op.create_index('ix_visits_patient_id', 'visits', ['patient_id'], unique=False)
    op.create_index('ix_visits_worker_id', 'visits', ['worker_id'], unique=False)
    op.create_table('risk_flags',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('visit_id', GUID(length=16), nullable=False),
    sa.Column('model_risk_level', sa.String(length=20), nullable=False),
    sa.Column('trend_adjusted_level', sa.String(length=20), nullable=False),
    sa.Column('trend_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_flags_created_at', 'risk_flags', ['created_at'], unique=False)
    op.create_index('ix_risk_flags_visit_id', 'risk_flags', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_flags_visit_id', table_name='risk_flags')
    op.drop_index('ix_risk_flags_created_at', table_name='risk_flags')
    op.drop_table('risk_flags')
    op.drop_index('ix_visits_worker_id', table_name='visits')
    op.drop_index('ix_visits_patient_id', table_name='visits')
    op.drop_index('ix_visits_created_locally_at', table_name='visits')
    op.drop_table('visits')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_patient_id', table_name='reviews')
    op.drop_index('ix_reviews_doctor_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_patients_worker_id', table_name='patients')
    op.drop_index('ix_patients_created_at', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_facility_id', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_facilities_name', table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
