"""add index on reviews.reviewed_at and visits.synced_at

Revision ID: e8f49d6bd808
Revises: 91595bfd8f8a
Create Date: 2026-08-19 14:31:11.572077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f49d6bd808'
down_revision = '91595bfd8f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reviews_reviewed_at', 'reviews', ['reviewed_at'], unique=False)
    op.create_index('ix_visits_synced_at', 'visits', ['synced_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visits_synced_at', table_name='visits')
    op.drop_index('ix_reviews_reviewed_at', table_name='reviews')
    # ### end Alembic commands ###
